version: "3.8"
services:
    backend:
        build: ./backend
        ports:
            - "9500:9500"
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - MONGO_URL=${MONGO_URL}
            - JWT_SECRET_KEY=${JWT_SECRET_KEY}
        depends_on:
            - redis
            - mongo
        restart: always
    redis:
        image: "redis:latest"
        ports:
            - "6379:6379"
        restart: always
    mongo:
        image: "mongo:latest"
        ports:
            - "27017:27017"
        restart: always
